name: cotwcompanion
description: Companion for the game theHunter Call of the Wild

publish_to: 'none'
version: 1.5.2+24

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  meta: ^1.8.0
  flutter_lints: ^2.0.1
  flutter_svg: ^1.1.0
  flutter_circular_text: ^0.3.1
  easy_localization: ^3.0.1
  shared_preferences: ^2.0.15
  auto_size_text: ^3.0.0
  horizontal_card_pager: ^1.1.1
  another_xlider: ^1.1.0
  omni_datetime_picker: ^0.1.0
  flutter_spinkit: ^5.1.0
  fl_chart: ^0.55.0
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.2
  package_info_plus: ^3.0.2
  wakelock: ^0.6.1+2
  easy_rich_text: ^1.0.4
  path_provider: ^2.0.10
  simple_shadow: ^0.3.0
  file_picker: ^5.2.4
  permission_handler: ^10.0.0
  provider: ^6.0.3
  async: ^2.9.0
  http: ^0.13.4
  internet_connection_checker: ^1.0.0+1
  flutter_cache_manager: ^3.3.0
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/raw/
    - assets/translations/
    - assets/graphics/icons/
    - assets/graphics/animals/
    - assets/graphics/reserves/
    - assets/graphics/weapons/
    - assets/graphics/callers/
    - assets/graphics/anatomy/
    - assets/graphics/heads/
    - assets/graphics/maps/hirschfeldenhuntingreserve/
    - assets/graphics/maps/laytonlakedistrict/
    - assets/graphics/maps/medvedtaiganationalpark/
    - assets/graphics/maps/vurhongasavannareserve/
    - assets/graphics/maps/parquefernando/
    - assets/graphics/maps/yukonvalley/
    - assets/graphics/maps/cuatrocolinasgamereserve/
    - assets/graphics/maps/silverridgepeaks/
    - assets/graphics/maps/teawaroanationalpark/
    - assets/graphics/maps/ranchodelarroyo/
    - assets/graphics/maps/mississippiacrespreserve/
    - assets/graphics/maps/revontulicoast/
    - assets/graphics/maps/newenglandmountains/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Font200.ttf
          weight: 200
        - asset: assets/fonts/Font300.ttf
          weight: 300
        - asset: assets/fonts/Font400.ttf
          weight: 400
        - asset: assets/fonts/Font500.ttf
          weight: 500
        - asset: assets/fonts/Font600.ttf
          weight: 600
        - asset: assets/fonts/Font700.ttf
          weight: 700
        - asset: assets/fonts/Font800.ttf
          weight: 800
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend400.ttf
          weight: 400