name: cotwcompanion
description: Companion for the game theHunter Call of the Wild

publish_to: 'none'
version: 1.6.0+32

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  meta: ^1.8.0
  flutter_lints: ^2.0.1
  flutter_svg: ^1.1.0
  flutter_circular_text: ^0.3.1
  easy_localization: ^3.0.1
  shared_preferences: ^2.0.15
  auto_size_text: ^3.0.0
  horizontal_card_pager: ^1.1.1
  another_xlider: ^1.1.0
  omni_datetime_picker: ^0.1.0
  flutter_spinkit: ^5.1.0
  fl_chart: ^0.55.0
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.2
  package_info_plus: ^3.0.2
  wakelock: ^0.6.1+2
  easy_rich_text: ^1.0.4
  path_provider: ^2.0.10
  simple_shadow: ^0.3.0
  file_picker: ^5.2.4
  permission_handler: ^10.0.0
  provider: ^6.0.3
  async: ^2.9.0
  http: ^0.13.4
  internet_connection_checker: ^1.0.0+1
  flutter_cache_manager: ^3.3.0
  logger: ^1.1.0
  latlng: ^0.2.0
  map: ^1.3.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/raw/
    - assets/translations/
    - assets/graphics/icons/
    - assets/graphics/icons/pngs/1/
    - assets/graphics/icons/pngs/2/
    - assets/graphics/icons/pngs/3/
    - assets/graphics/animals/
    - assets/graphics/animals/pngs/
    - assets/graphics/reserves/
    - assets/graphics/weapons/
    - assets/graphics/callers/
    - assets/graphics/anatomy/
    - assets/graphics/heads/
    - assets/graphics/maps/hirschfeldenhuntingreserve/1/
    - assets/graphics/maps/hirschfeldenhuntingreserve/2/
    - assets/graphics/maps/hirschfeldenhuntingreserve/3/
    - assets/graphics/maps/laytonlakedistrict/1/
    - assets/graphics/maps/laytonlakedistrict/2/
    - assets/graphics/maps/laytonlakedistrict/3/
    - assets/graphics/maps/medvedtaiganationalpark/1/
    - assets/graphics/maps/medvedtaiganationalpark/2/
    - assets/graphics/maps/medvedtaiganationalpark/3/
    - assets/graphics/maps/vurhongasavannareserve/1/
    - assets/graphics/maps/vurhongasavannareserve/2/
    - assets/graphics/maps/vurhongasavannareserve/3/
    - assets/graphics/maps/parquefernando/1/
    - assets/graphics/maps/parquefernando/2/
    - assets/graphics/maps/parquefernando/3/
    - assets/graphics/maps/yukonvalley/1/
    - assets/graphics/maps/yukonvalley/2/
    - assets/graphics/maps/yukonvalley/3/
    - assets/graphics/maps/cuatrocolinasgamereserve/1/
    - assets/graphics/maps/cuatrocolinasgamereserve/2/
    - assets/graphics/maps/cuatrocolinasgamereserve/3/
    - assets/graphics/maps/silverridgepeaks/1/
    - assets/graphics/maps/silverridgepeaks/2/
    - assets/graphics/maps/silverridgepeaks/3/
    - assets/graphics/maps/teawaroanationalpark/1/
    - assets/graphics/maps/teawaroanationalpark/2/
    - assets/graphics/maps/teawaroanationalpark/3/
    - assets/graphics/maps/ranchodelarroyo/1/
    - assets/graphics/maps/ranchodelarroyo/2/
    - assets/graphics/maps/ranchodelarroyo/3/
    - assets/graphics/maps/mississippiacrespreserve/1/
    - assets/graphics/maps/mississippiacrespreserve/2/
    - assets/graphics/maps/mississippiacrespreserve/3/
    - assets/graphics/maps/revontulicoast/1/
    - assets/graphics/maps/revontulicoast/2/
    - assets/graphics/maps/revontulicoast/3/
    - assets/graphics/maps/newenglandmountains/1/
    - assets/graphics/maps/newenglandmountains/2/
    - assets/graphics/maps/newenglandmountains/3/
  fonts:
    - family: Text
      fonts:
        - asset: assets/fonts/Font200.ttf
          weight: 200
        - asset: assets/fonts/Font300.ttf
          weight: 300
        - asset: assets/fonts/Font400.ttf
          weight: 400
        - asset: assets/fonts/Font500.ttf
          weight: 500
        - asset: assets/fonts/Font600.ttf
          weight: 600
        - asset: assets/fonts/Font700.ttf
          weight: 700
        - asset: assets/fonts/Font800.ttf
          weight: 800
    - family: Title
      fonts:
        - asset: assets/fonts/Title200.ttf
          weight: 200
        - asset: assets/fonts/Title300.ttf
          weight: 300
        - asset: assets/fonts/Title400.ttf
          weight: 400
        - asset: assets/fonts/Title500.ttf
          weight: 500
        - asset: assets/fonts/Title600.ttf
          weight: 600
        - asset: assets/fonts/Title700.ttf
          weight: 700
        - asset: assets/fonts/Title800.ttf
          weight: 800